# Generated by Django 4.2.16 on 2024-10-12 23:13

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='panels',
            field=wagtail.fields.StreamField([('qualified_charitable', 5), ('corporate_sponsors', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('description', 2), ('cta_text', 3), ('cta_link', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('description', 2), ('items', 7), ('cta_text', 3), ('cta_link', 4)]], {})}, null=True),
        ),
    ]
