# Generated by Django 4.2.16 on 2024-10-13 02:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0007_alter_homepage_panels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('blog_section', models.CharField(blank=True, help_text='Blog section intro text', max_length=250)),
                ('resources_section', models.CharField(blank=True, help_text='Resources section intro text', max_length=250)),
                ('therapy_section', models.CharField(blank=True, help_text='Therapy section intro text', max_length=250)),
                ('service_name', models.CharField(max_length=250)),
                ('service_description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
