# Generated by Django 4.2.16 on 2024-10-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_gdrivepage_hero_cta_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='files',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='hero_text',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdrivepage',
            name='intro',
            field=models.CharField(blank=True, help_text='Short intro text', max_length=250),
        ),
        migrations.AddField(
            model_name='gdrivepage',
            name='selected_files',
            field=models.ManyToManyField(blank=True, related_name='pages', to='home.file'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='home.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.folder'),
        ),
    ]
