# Generated by Django 4.2.16 on 2024-10-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_panels'),
        ('home', '0009_postpage_therapypage_blogpage'),
    ]

    operations = [
    ]
