# Generated by Django 4.2.16 on 2024-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_folder_parent_folder_remove_gdrivepage_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('files', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='gdrivepage',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='gdrive_pages', to='home.file'),
        ),
    ]
