# Generated by Django 4.2.16 on 2024-10-13 05:28

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20241012_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='therapypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='blog_section',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='resources_section',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='therapy_section',
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('button', 6), ('video', 9), ('blog_posts', 16), ('video_posts', 18), ('files', 23), ('content', 30)], blank=True, block_lookup={0: ('home.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('button_text', 4), ('button_url', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Embed URL for the video'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional video title', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('video_url', 7), ('video_title', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the blog post', 'max_length': 250}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short introduction or summary of the blog post'}), 12: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date'}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the full blog post'}), 14: ('wagtail.blocks.StructBlock', [[('title', 10), ('intro', 11), ('date', 12), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('blog_posts', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (9,), {}), 18: ('wagtail.blocks.StructBlock', [[('videos', 17)]], {}), 19: ('wagtail.blocks.FieldBlock', (), {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short description of the file', 'max_length': 250, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('file', 19), ('description', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('files', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 25: ('wagtail.blocks.RichTextBlock', (), {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 27: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 28: ('wagtail.blocks.CharBlock', (), {}), 29: ('wagtail.blocks.StreamBlock', [[('heading', 28), ('paragraph', 25), ('image', 1), ('video', 26), ('document', 27)]], {'max_num': 1}), 30: ('wagtail.blocks.StreamBlock', [[('heading', 24), ('paragraph', 25), ('image', 1), ('video', 26), ('document', 27), ('nested_content', 29)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='intro',
            field=models.CharField(blank=True, help_text='Short intro text', max_length=250),
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='PostPage',
        ),
        migrations.DeleteModel(
            name='TherapyPage',
        ),
    ]
