# Generated by Django 4.2.16 on 2024-10-13 14:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_file_gdrivepage_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='files',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='gdrivepage',
            name='files',
        ),
        migrations.CreateModel(
            name='GDrivePageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.file')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_drive_page_files', to='home.gdrivepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
