# Generated by Django 4.2.16 on 2024-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_files_file_url_remove_gdrivepage_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gdrivepagefile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
