# Generated by Django 4.2.16 on 2024-10-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_file_id_alter_gdrivepagefile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdrivepagefile',
            old_name='image',
            new_name='file',
        ),
    ]
