# Generated by Django 4.2.16 on 2024-10-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20241013_0414'),
        ('home', '0013_addpage_remove_homepage_panels_alter_homepage_body_and_more'),
    ]

    operations = [
    ]
