# Generated by Django 4.2.16 on 2024-10-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_image_gdrivepagefile_file'),
        ('home', '0016_navigationitem'),
    ]

    operations = [
    ]
