# Generated by Django 4.2.16 on 2024-10-13 19:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0018_remove_navigationitem_page_gdrivepage_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdrivepage',
            name='user_groups',
        ),
        migrations.CreateModel(
            name='GDriveGroup',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdrive_groups', to='home.gdrivepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
