# Generated by Django 4.2.16 on 2024-10-13 19:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0019_remove_gdrivepage_user_groups_gdrivegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdrivegroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='gdrivegroup',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='gdrivegroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='gdrivegroup',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_drive_groups', to='home.gdrivepage'),
        ),
    ]
