# Generated by Django 4.2.16 on 2024-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0020_alter_gdrivegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivepage',
            name='g_drive_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='GDriveGroup',
        ),
    ]
