# Generated by Django 4.2.16 on 2024-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_gdrivepage_g_drive_groups_gdrivegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
